### ISSUE TITLE
Issue with fetching my vault

### ISSUE THREAD

**Issue by francescofeston** [secure-77/Perlite#116]
Dear Secure 77, 

first of all thank you for this tool, it's amazing. 
I have managed to set it up and it works properly, the only issue is that what's loaded into the viewer is the "demo" Obsidian vault and not my own. 
I have adjusted all the settings as per instructions (I followed both yours and and those of https://blog.nihilism.network/servers/perlite/)
The result can be seen in the screenshot attached
![Schermata 2024-02-03 alle 23 40 09](https://github.com/secure-77/Perlite/assets/30663579/37dec6f4-123d-4a6d-937b-eb709b75f781)

The top folder is my own but it cannot be accessed. 
I know it may be some trivial oversight from my side and Please bear with me because I do not have a computer science background. 
Thank you for your help in troubleshooting this one. 
francesco

**Comment by secure-77** [comment]
Hey @francescofeston,

Can you tell me where you have set your vault to `Actionable-Knowledge` ?

For me it looks like you have adjusted the helper.php, but only set the `$vaultName` to your vault instead of the `$rootDir`. So you also need to replace this line:

`$rootDir = empty(getenv('NOTES_PATH')) ? 'Demo' : getenv('NOTES_PATH');`

with this

`$rootDir = "Actionable-Knowledge`

BR,
sec77

**Comment by secure-77** [comment]
You are welcome, glad it worked 👍 

In Obsidian you can download custom themes via the settings, after you have installed one there should be the themes folder.

![image](https://github.com/secure-77/Perlite/assets/31564517/c326a709-3133-425c-9fe4-9f110234598e)
