### ISSUE TITLE
Support for Tasks Syntax

### ISSUE THREAD

**Issue by LILKEK361** [secure-77/Perlite#118]
Hello,
I justed installed Perlite on my Raspy and hooked it up with syncthing so it has my notes.
But I run into a problem where my Task and and footnotes aren't convertet like they should in Obsidian.

![Perlite online view](https://github.com/secure-77/Perlite/assets/115891787/aeee4744-7e60-42e7-9586-60b7a11e667b)

As one can see in the image the footnotes and task aren't convertet.
Is this normal?

**Comment by secure-77** [comment]
Yes, these both features are not implemented yet. for the footnotes there exists already a issue #9 and back then I hoped for some update of the parsedown library which Im using. But it seems this will never happen as there are no updates since years. At least for the Tasks I will try to implement this by myself. 

So I will use this issue as tracker for the Task implementation

**Comment by secure-77** [comment]
implemented in release [1.5.9](https://github.com/secure-77/Perlite/releases/tag/1.5.9)
