### ISSUE TITLE
A duplicate path error occurs when reading files or folders with multi byte chars (e.g. chinese chars)

### ISSUE THREAD

**Issue by Darkluna999** [secure-77/Perlite#4]
A duplicate path error occurs when reading a partial folder
For example: D:/abc/bcd.md
is read as D:/abc/abc/bcd.md
Causes an error

**Comment by secure-77** [comment]
Hey @Darkluna999,

can you please provide some additional information, like 

- on which os do you run the server? 
- where does the error message show up?
- your folder structure 

Thanks and BR,
Sec77

**Comment by Darkluna999** [comment]
* on which os do you run the server?
    * both Windows-VCS-php7.4 and CentOS-nginx-php7.3
* where does the error message show up?
    * When I click on the md file in the list on the left, the display column on the right
    > Warning: file_get_contents(D:\darkluna\perlite/OB/Academic/结直肠/结直肠/结直肠癌新辅助化疗DLM cCR pCR分析.md): failed to open stream: No such file or directory in D:\darkluna\perlite\content.php on line 123
    * But in fact the file path itself is:"D:\darkluna\perlite/OB/Academic/结直肠/结直肠癌新辅助化疗DLM cCR pCR分析.md"
    * This phenomenon only occurs in a specific two folders, and when I move files to other folders, this problem does not occur again
* your folder structure
    *The problem only occurs in the 结直肠 and 其他日志 folder
[1.txt](https://github.com/secure-77/Perlite/files/8153599/1.txt)

**Comment by secure-77** [comment]
Hey @Darkluna999 

I could reproduce the problem and i think i fixed it, the problem was the php basename function which (per default) does not support multi byte utf, i added a custom basename_mb function to fix this problem.

![image](https://user-images.githubusercontent.com/31564517/156025908-2c1c26f8-4769-4e7c-a8e6-aa7f1f3efbf5.png)


please use the latest commit of helper.php and let me know if this fixes you problem: https://github.com/secure-77/Perlite/blob/7a1e9b2fb21b0fa0d35d9aca8dd9128952320434/perlite/helper.php
Thanks!

BR,
Sec77

**Comment by Darkluna999** [comment]
wow，yes，it is fied now！

**Comment by secure-77** [comment]
nice, glad to hear the fix is working 👍
