### ISSUE TITLE
Support image resizing

### ISSUE THREAD

**Issue by JohnnyHenver** [secure-77/Perlite#54]
**Is your feature request related to a problem? Please describe.**

Obsidian established the following syntax to rescale images:
`![[og-image.png|200]]`
This currently breaks the image links in Perlite.

**Describe the solution you'd like**

It would be great if Perlite could support scaled images the way Obsidian does.

**Describe alternatives you've considered**

Scaling the images outside of obsidian is valid, but kind of a hassle.

**Comment by shervinsahba** [comment]
This would be great. As an example, currently `![[image.png|100]]` is parsed as a plaintext `!` followed by the renamed wikilink to image.png:

![image](https://user-images.githubusercontent.com/25020522/215689140-bc2672b8-8ac7-446a-8c77-e2f9225875b8.png)

We can convert all images beforehand, but it'd be awesome to have them rescale in Perlite. And if not, it'd be nice if the image itself still appeared.

I'm taking guesses because of my unfamiliarity with the codebase, but is this issue occurring in Parsedown.php at the `inlineImage` call? 

https://github.com/secure-77/Perlite/blob/ac8c431e132ce379134348fdc91010c9b7cf6bc1/perlite/Parsedown.php#L1224-L1238

And thus does it stem from the regex calls in the  inlineLink function in PerliteParsedown.php?

https://github.com/secure-77/Perlite/blob/ac8c431e132ce379134348fdc91010c9b7cf6bc1/perlite/PerliteParsedown.php#L498-L560

Trying to wrap my head around it...

**Comment by secure-77** [comment]
This is fixed in version 1.5.3
