### ISSUE TITLE
I have some problems with footnotes and graph

### ISSUE THREAD

**Issue by Darkluna999** [secure-77/Perlite#8]
1. First, I noticed that the footnotes in the text didn't show up properly, but rather as normal text and couldn't jump hyperlinks.
![image](https://user-images.githubusercontent.com/53258301/157089230-0328e809-fae6-48b9-b0eb-55e83aa6eb62.png)
![image](https://user-images.githubusercontent.com/53258301/157089291-9923f1de-62bd-4e12-b502-ce6a5a82ffc1.png)

2. Secondly, my graph moudle has not been able to load, but I have not found any difference compared to the code.
But what I noticed is that unlike your demo web page, the "Open-graph" button flashed for a moment and then disappeared.
Not just my folder, but also the demo folder.
![image](https://user-images.githubusercontent.com/53258301/157089558-63a2ab48-683a-4653-addb-6eaedb7cda8d.png)
![image](https://user-images.githubusercontent.com/53258301/157091123-1c0f188b-260e-4ade-9c20-0a84ff0b17d5.png)

nginx 1.21.0
PHP 7.4.0

**Comment by secure-77** [comment]
Hi,

Regarding:
1. iam not sure what you mean, as i cant read Chinese. Please provide me a demo file that i can compare it between Obsidian and Perlite

2.  this usually happens when there is no metabase.json in the root directory of your vault

**Comment by Darkluna999** [comment]
1. the example of footnote...
[Example.md](https://github.com/secure-77/Perlite/files/8200429/Example.md)
 2. no, I have put it there and even just put your demo folder, but it does not work, too

**Comment by secure-77** [comment]
please take a look at the new created issue for this: #9 
at the moment this can only be implemented by turning the safeMode off (not recommended) and including the ParsedownExtra.php. If you want to do this, you need to do this by yourself (only 3 lines of code needed to be adjust). but i wont implement it in this project yet.

regarding your graph problem, without an error message its really hard to say what the problem is. only thing what i can suggest you is to make sure your folder structure is correct and the metabase.json is on the correct place. 

![image](https://user-images.githubusercontent.com/31564517/157115005-f54c4de4-19f1-454e-8a07-5fdcd9f1eee5.png)

![image](https://user-images.githubusercontent.com/31564517/157115072-f514334d-ea14-455c-8cd7-4ddf4d1d2584.png)

finally you can try to set your root folder hardcoded in the helper.php like this:

![image](https://user-images.githubusercontent.com/31564517/157115234-cebefbe8-7aac-4d06-8c9c-3f1ba6067285.png)

**Comment by Darkluna999** [comment]
Good! I will check my file structure as soon as possible

**Comment by secure-77** [comment]
from you screenshot i can see that you root folder is actually "Notes" and not "Demo". So this might be the problem. 
for testing purpose, replace your Notes folder with the Demo folder and the graph should be available.

**Comment by Darkluna999** [comment]
Wow! You've found blind spots! Indeed he works well!

**Comment by secure-77** [comment]
glad you have fixet it, you are welcome!
