### ISSUE TITLE
Display nodes that don't exist yet on the graph

### ISSUE THREAD

**Issue by BuyMyMojo** [secure-77/Perlite#96]
**Is your feature request related to a problem? Please describe.**
In Obsidian's own graph links to non-existing pages are still displayed but in a different colour, I would like to see this in Perlite

**Describe the solution you'd like**
Possibly a toggle in the settings on the graph page and in the helper.php file

**Additional context**
Obsidian graph:
![image](https://github.com/secure-77/Perlite/assets/46948241/15ccfba7-4aa6-4738-9247-a8084de8eff0)

Perlite graph of the same vault:
![image](https://github.com/secure-77/Perlite/assets/46948241/b991bbf1-c30e-4275-b27c-1c18046074a3)

**Comment by secure-77** [comment]
Thanks for your request.

Can you please give me some background on why this would be useful? I understand that this is useful in Obsidian because it is the editor and you can quickly see if a file is missing. For Perlite as a "read only" system, I can't see the benefit to the "reader" in how it would help them see that a node is missing.

Besides the "why question", there are some technical / security issues:

The detection of whether a node is present or not is already implemented, as this provides the ability to exclude nodes that one would not want to make available to the public. So the intention is to exclude these notes from the graph, as you also don't want to reveal sensitive file names (for security reasons). The filtering is done by the php engine, and it would need a property (for each missing node) to identify it in the fronted (js) and give it its own color. The notes in the vis.js library don't have many ways to store properties, so probably some (ugly) workaround is needed to get this.

It's not impossible to implement, but without a good reason I don't think it's worth the effort.

**Comment by BuyMyMojo** [comment]
I have two reasons myself:
- I like sharing my vaults with the uncreated notes linked and would like for people to be able to request a not on a specific yet to be created note to be created
- sharing an overview with the graph of world building stuff is very useful, having uncreated notes linked would let me create the intermediate links between two areas of the world without having that link written yet

**Comment by secure-77** [comment]
I think both of your points could be achieved by just create a empty node an give it aome idicator in the file name like (WIP).

But I will check how much effort this is,
maybe I can use the link property (as in this case there is no link available) to store this information and change the color based on this.
